version: "3"

services:
  mongodb:
    image: mongo

  web-api:
    build: ./web-api
    ports:
      - "4001:4001"
    volumes:
      - /app/node_modules
      - ./web-api:/app/web-api

  web-ui:
    build: ./web-ui
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./web-ui:/app/web-ui
